spring.application.name=helpdesk_backend
# DB Connection Params
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=deepcoder

# hibernate settings
spring.jpa.hibernate.ddl-auto=update

# port number
# server.port=8080